[package]
name = "shapes"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
